name: Build and publish

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Image version formatted as X.Y.Z
        required: false

permissions:
  contents: read
  packages: write

defaults:
  run:
    working-directory: ./scripts
    shell: pwsh

jobs:
  BuildAndPublish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and push
        env:
          VERSION: ${{ github.event.inputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./build.ps1 -GitHubPat $env:GITHUB_TOKEN -Version $env:VERSION
